First release
wirenboard/wb-nm-helper pull request #1
Opened 2022-06-23 09:32 UTC by KraPete

Добавил базовую поддержку NM

Старый конфиг остаётся и его можно редактировать как раньше, всё будет записано в /etc/network/interfaces.
loopback и can тоже только через /etc/network/interfaces, т.к. NM их не умеет.
Новые соединения можно создавать только в NM.

![изображение](https://user-images.githubusercontent.com/86825564/175267136-6b58565d-28b8-4393-8ba2-1e73ca513957.png)

![изображение](https://user-images.githubusercontent.com/86825564/175267168-c540e831-3b1c-42d5-bb6e-db8aaf63aa64.png)

![изображение](https://user-images.githubusercontent.com/86825564/175267200-f5dda83b-9c31-4b84-8bfd-2741dd1b2764.png)

2022-10-06 05:29 UTC, KraPete commented
* Убрал `интерфейс`, сделал `соединение`.
* Добавил возможность редактировать название соединения в NM.
* Добавил список доступных WiFi сетей. Обновляется по F5
* Добавил список подходящих для соединения устройств. Тоже обновляется по F5
* Добавил выбор SIM-слота.

![изображение](https://user-images.githubusercontent.com/86825564/194221467-a555a03f-498d-47f5-8513-b076fb81ce57.png)

![изображение](https://user-images.githubusercontent.com/86825564/194221649-b83f1186-7db3-4983-a5c1-511b5afa11fb.png)

![изображение](https://user-images.githubusercontent.com/86825564/194221784-ac4b0bd1-16b9-48a7-af97-44f8cbcf568c.png)

2022-10-10 11:56 UTC, KraPete commented
Доработал интерфейс.
- Список соединений сортируется по типу
- У каждого соединения есть иконка типа
- При создании соединения появляется окно выбора типа. Потом его изменить уже нельзя. Редактор типа на конретной вкладке отключен.

Стало так
![изображение](https://user-images.githubusercontent.com/86825564/194860595-95f3bed0-ecdc-40bc-b328-1f79ceb058f0.png)
![изображение](https://user-images.githubusercontent.com/86825564/194860725-22fda5d9-7fa7-430a-a944-16d0c5983299.png)

2022-10-20 08:53 UTC, webconn requested changes
Я ещё не всё отсмотрел, осталась прослойка modemmanager и /etc/network/interfaces

2022-10-20 08:53 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +            logging.debug('Deactivate active connection "%s"', old_active_connection_id)
`extra`? Причём для старого соединения

2022-10-20 08:53 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +            if not mm.set_primary_sim_slot(dev_path, sim_slot):
Будет классно однажды эту логику в networkmanager перетащить... Может, там какие-нибудь pre-up скрипты есть и конфликты соединений? Например, как когда выбираешь другое wi-fi соединение

2022-10-20 08:53 UTC, webconn commented on wb/nm_helper/network_managing_system.py
> +class INetworkManagingSystem(object):
`Management`, и в py3 наследоваться от `object` не надо (здесь и во всех остальных классах)

2022-10-20 08:53 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> +    set_opt(res, "ipv4.hostname", cfg, "ipv4.dhcp-hostname")
Вот с унификацией полей в схеме с документацией nm можно будет избавиться от этих простыней

2022-10-20 10:53 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +            if not mm.set_primary_sim_slot(dev_path, sim_slot):
Там фильтры. Когда просишь поднять соединение, NM ищет подходящее устройство и для него поднимает соединение. Тут же нам надо выключить одно, перенастроить устройство, включить другое.

2022-10-20 10:54 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +    return "".join(map(lambda item: "%c" % item, data))
Тут приходит `dbus.Array[dbus.Byte]`, у которого нет `decode`

2022-10-20 10:57 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +def get_opt(opt_dict, path, default=None):
Я сделал, чтоб оно работало и с `dict`, и с `dbus.Dictionary`. Первый нужен для JSON, второй - для запросов и ответов `dbus`.
В C++ бы работала перегрузка функции по параметрам, и было бы 2 функции, как это в питоне сделать, я не знаю. Если только 2 функции с разными именами.

2022-10-20 10:58 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        logging.debug('Activate connection "%s"', cn_id)
`extra` я использую для фильтрации повторяющихся сообщений в не `debug` режиме. В `debug` пусть всё сыпется.

2022-10-20 10:59 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +            logging.debug('Device for connection "%s" is not found', cn_id)
Опять же `debug` пусть всё видно будет

2022-10-20 11:02 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                            logging.debug("Error during connections deactivation: %s", ex)
Не хочу засорять логи. Ну не закрылось менее приоритетное соединение и пофиг. В следующей итерации закроется

2022-10-20 11:02 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    buffer = BytesIO()
`urlopen` не умеет в указание интерфейса для посылки запроса

2022-10-20 11:29 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    connection_ids: list[str], active_connections: dict[str:NMActiveConnection]
Поправил

2022-10-20 11:29 UTC, KraPete commented on wb/nm_helper/network_manager.py
> +    def find_connection(self, cn_id: str) -> NMConnection:
Поправил

2022-10-20 13:26 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +# Use NM's implementation after fixing the bug
Добавил

2022-10-20 13:26 UTC, KraPete commented on wb/nm_helper/network_managing_system.py
> +class INetworkManagingSystem(object):
Убрал

2022-10-21 08:53 UTC, webconn commented on debian/control
> +Depends: ${misc:Depends}, python3 (>= 3.5), python3-wb-nm-helper (= ${binary:Version}), wb-mqtt-homeui (>= 2.47.0)
Ну вот я с этим столкнулся, когда решил установить этот пакет и homeui из ветки, зависимости не разрешились, пришлось шаманить

2022-10-21 08:54 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> +def get_opt(opt_dict, path, default=None):
В питоне можно типы в рантайме сравнивать через if

2022-10-21 08:55 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    signal.signal(signal.SIGINT, signal.SIG_DFL)
C `KeyboardInterrupt` три строчки, и так в целом принято. Плюс ошибки из цикла ловить и писать в лог в этом же `try/except` удобней

2022-10-21 08:56 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +                            logging.debug("Error during connections deactivation: %s", ex)
Ну а так мы получим неконсистентное состояние системы без всякой информации об этом (если дебаг выключен, что чаще правда). Хотя бы warning уж. Мне не кажется, что незакрытое соединение - это хорошо

2022-10-21 08:57 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +            if not mm.set_primary_sim_slot(dev_path, sim_slot):
А устройство там технически не одно и то же будет?

2022-10-21 13:28 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +            if not mm.set_primary_sim_slot(dev_path, sim_slot):
Неа. Оно появится на шине по другому пути

2022-10-21 13:32 UTC, KraPete commented
@webconn Сделал, чтоб названия параметров были одинаковыми. Фактически, конечно они разные, т.к. в json неудобно иметь названия параметров с точкой. Заворачивать все пути с точкой во вложенные объекты тоже не вариант, т.к. теряется возможность расположить поля на форме в произвольном порядке. С другой строны некоторые пути надо делать вложенными объектами, чтобы красиво отрисовывался выбор вариантов.

2022-10-24 07:43 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +                            logging.debug("Error during connections deactivation: %s", ex)
Я всё-таки считаю, что это неправильно

2022-10-24 07:43 UTC, webconn commented on wb/nm_helper/nm_helper.py
> +        adapter.add_devices(devices)
`add_devices` вроде возвращала модифицированный массив, может, лучше этой нотации и следовать?

2022-10-24 07:43 UTC, webconn commented on wb/nm_helper/nm_helper.py
> +        interfaces = interfaces + adapter.read()
Неочевидное название для метода `read`, не вполне понятно, что он читает. `get_interfaces` ведь отлично подошло бы?

2022-10-24 07:51 UTC, KraPete commented on wb-network.schema.json
> +            "title": "Wi-Fi access point",
Нет. Для AP надо другой список возможных типов работы с ipv4. Там нельзя сделать `manual` и `auto`, а надо ставить `shared`. Так что пришлось выделить отдельный тип. Не смог придумать как иначе в json-editor впихнуть.

2022-10-24 07:53 UTC, KraPete commented on wb-network.schema.json
> +                            "default": 1,
![изображение](https://user-images.githubusercontent.com/86825564/197475173-350f9d30-63a4-4976-9fb9-923e543a4a9b.png)
К сожалению, в json-editor нет возможности задать произвольный текст в выпадающем списке, который бы обозначал, что параметр отсутствует.

2022-10-24 07:54 UTC, KraPete commented on wb-network.schema.json
> +        "nm_connection": {
`ipv4` отличается для `WiFi AP`, у остальных да, одинаковый

2022-10-24 07:57 UTC, KraPete commented on wb-network.schema.json
> +                "netmask": {
Я чё-то посмотрел, что везде в интерфейсах оно отделено, и оставил.

2022-10-24 08:15 UTC, webconn commented on wb-network.schema.json
> +                "netmask": {
Ну ладно

2022-10-24 08:16 UTC, webconn commented on wb-network.schema.json
> +                            "default": 1,
А, это с галочкой вместе идёт. Тогда ок

2022-10-24 10:39 UTC, KraPete commented on wb/nm_helper/nm_helper.py
> +        interfaces = interfaces + adapter.read()
Переименовал в `get_connections`

2022-10-24 10:40 UTC, KraPete commented on wb/nm_helper/nm_helper.py
> +        adapter.add_devices(devices)
сделал `get_devices`, который возвращает список

2022-10-24 10:40 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +def get_opt(opt_dict, path, default=None):
Вообще переписал всё тут

2022-10-24 10:41 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                            logging.debug("Error during connections deactivation: %s", ex)
Сделал `warning`

2022-10-24 10:41 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    res = {}
Вообще переписал это место

2022-10-24 10:42 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +    set_opt(res, "ipv4.hostname", cfg, "ipv4.dhcp-hostname")
Эти простыни убрал, добавил другие

2022-10-24 11:19 UTC, KraPete commented on wb-network.schema.json
> +            "title": "Wi-Fi access point",
Насколько я понимаю, для ad-hoc надо делать статический ip. `shared` можно делать для соединений, которые раздают интернет или для запуска dhcp сервера

2022-10-27 04:33 UTC, KraPete commented
Поправил создание точки доступа и перезапуск сервисов, чтоб настройки без перезагрузки применялись

2022-10-27 05:55 UTC, webconn commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
А почему не namedtuple или что-нибудь такое? Иммутабельные типы лучше ведь, и вроде объекты `DeviceDesc` конструируются на месте и не дополняются в коде => заедет бесплатно

2022-10-27 05:55 UTC, webconn commented on wb/nm_helper/nm_helper.py
> +        os.system("systemctl stop wb-connection-manager")
Это так запланировано, что сервис тут только останавливается и не запускается обратно?

2022-10-27 06:01 UTC, KraPete commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
`namedtuple` сериализуется в JSON как массив, без ключей, а тут я хочу нормальный обЪект с названиями полей

2022-10-27 06:02 UTC, KraPete commented on wb/nm_helper/nm_helper.py
> +        os.system("systemctl stop wb-connection-manager")
его потом `wb-mqtt-confed` запускает

2022-10-27 06:26 UTC, webconn commented on wb/nm_helper/nm_helper.py
> +        os.system("systemctl stop wb-connection-manager")
Запутанное. Допиши в коммент сюда, что ли, а то потом кто-то кроме меня будет тут голову чесать

2022-10-27 06:27 UTC, webconn commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
О как, ну тогда ладно

2022-10-27 07:16 UTC, KraPete commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
Можно так [так](https://chadrick-kwag.net/json-dumpingserializing-custom-python-classes/), но кода много получается

2022-10-27 07:28 UTC, webconn commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
Ну да, не стоит того сейчас

2022-10-28 07:18 UTC, KraPete commented on wb/nm_helper/nm_helper.py
> +        os.system("systemctl stop wb-connection-manager")
Дописал

2022-10-28 07:20 UTC, KraPete commented
Сделал, чтобы при установке пакета проверялся `/etc/network/interfaces`. Если он не редактировался пользователем, то заменяем его на заглушку и передаём управление NM.

2022-10-28 07:21 UTC, vdromanov commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
мб здесь поможет namedtuple._asdict() ?

2022-10-28 07:49 UTC, KraPete commented on wb/nm_helper/network_management_system.py
> +class DeviceDesc(TypedDict):
Всё равно надо писать свой `encoder`

2022-10-28 14:54 UTC, webconn requested changes

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.postinst
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig || true
Не хватает `#DEBHELPER#` тут или в начале

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.preinst
> +
Аналогично про `#DEBHELPER#`

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.postinst
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig || true
Не надо таскать чужие файлы, лучше PR в confed сделать, который этот файл удалит

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.prerm
> +        cp /etc/network/interfaces.wb /etc/network/interfaces
`intefaces.wb` - это тоже чужой файл (из displace в wb-configs). Для своей резервной копии надо сделать свой суффикс.

А ещё манипуляции с конфигами надо проводить при `purge`, при обычном удалении пакетов это так себе практика

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.prerm
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json || true
`#DEBHELPER#`

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.preinst
> +    if [ "`md5sum /etc/network/interfaces.wb | cut -d' ' -f 1`" == "`md5sum /etc/network/interfaces | cut -d' ' -f 1`" ] ; then
Не стоит рассчитывать на файл `.wb`, он не обязательно оригинальный, это просто так получилось в какой-то момент. Лучше сюда вхардкодить чексумму.

А ещё все манипуляции с чужими конфигами надо сопровождать хотя бы сообщением в stdout

2022-10-28 14:54 UTC, webconn commented on debian/wb-nm-helper.preinst
> +        deb-systemd-invoke disable hostapd || true
Ненадёжно, при обновлении фитом они обратно включатся. `hostapd` нужен для networkmanager зачем-нибудь? Может, нам пакет вообще вынести?

Если не выносить пакет, то лучше ExecCondition добавить и для hostapd, и для dnsmasq в override.conf

2022-10-28 14:58 UTC, KraPete commented on debian/wb-nm-helper.postinst
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig || true
Добавил

2022-10-28 14:58 UTC, KraPete commented on debian/wb-nm-helper.preinst
> +
Добавил

2022-10-28 15:03 UTC, KraPete commented on debian/wb-nm-helper.postinst
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig || true
Нет. Мы ж этот пакет по желанию ставим. Т.е. когда стоит confed, должен быть интерфейс от confed. А когда поставили этот пакет, убрать интерфейс от confed и использовать из этого пакета. Но самое приятное, что после удаления этого пакета надо вернуть настройки от confed. Какой надо делать PR в конфед, чтоб всё это провернуть?

2022-10-28 15:08 UTC, KraPete commented on debian/wb-nm-helper.prerm
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json || true
Добавил

2022-10-28 15:14 UTC, KraPete commented on debian/wb-nm-helper.preinst
> +        deb-systemd-invoke disable hostapd || true
Если настроена точка доступа через interfaces, надо hostapd. Добавлю ExecCondition

2022-10-29 05:00 UTC, KraPete commented on debian/wb-nm-helper.preinst
> +        deb-systemd-invoke disable hostapd || true
С фитом вообще классные спецэффекты. Поставили wb-nm-helper, оно притащило NM и MM, снесло /etc/network/interfaces. И тут накатили фит. Фит снёс wb-nm-helper, NM и MM, а /etc/network/interfaces пустой. Всё, мы сидим без сети.

2022-10-31 07:51 UTC, webconn commented on debian/wb-nm-helper.postinst
> +mv -f /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json /usr/share/wb-mqtt-confed/schemas/interfaces.schema.json-orig || true
Тогда можно использовать `dpkg-divert`, он позволяет перетаскивать файлы чужих пакетов, не ломая при этом логику обновления этих пакетов

2022-11-08 10:26 UTC, KraPete commented
Rebase https://github.com/wirenboard/wb-nm-helper/pull/2

2022-11-08 10:26 UTC, closed without merging