Update connections description
wirenboard/wb-nm-helper pull request #12
Opened 2022-11-14 07:22 UTC by KraPete

Update description for connections configured in /etc/network/interfaces

2022-11-17 17:18 UTC, wb-adegtyarev reviewed
Ещё предлагаю вот это переписать:
con_switch_desc
Сейчас:
> Сервис предназначен для переключения на резервные соединения при потери связи через основное. Периодически проверяется доступность сети через текущее соединение. Если оно работает некорректно, активируется следующее по списку. Если более приоритетное соединение снова стало доступным, сервис переключится на него и закроет текущее резервное соединение.

Предложение:
> Контроллер каждые 5 секунд проверяет связь с интернетом, если связи нет — текущее соединение завершится и будет активировано следующее по списку. Далее контроллер каждые 60 секунд попытается поднять одно из соединений с более высоким приоритетом и, если это удастся, то переключится на него.

2022-11-18 04:32 UTC, KraPete commented on wb-network.schema.json
> +            "can_description": "Настроено в /etc/network/interfaces. Если необходимо настроить это соединение в NetworkManager'е, удалите и создайте новое",
Удалить можно как угодно. Если хочется хардкора, можно руками в файле, но, навереное, проще из web-интерфейса, в нём тоже можно.

2022-11-21 05:19 UTC, webconn requested changes

2022-11-21 05:19 UTC, webconn commented on wb-network.schema.json
> +            "can_description": "Настроено в /etc/network/interfaces. Если необходимо настроить это соединение в NetworkManager'е, удалите и создайте новое",
В версии описания для обычной сети хочется больше настойчивости:

```suggestion
            "can_description": "Настроено в /etc/network/interfaces. Этот интерфейс нельзя настроить для автоматического переключения, пока он не управляется через NetworkManager. Для перехода на NetworkManager удалите и создайте его заново",
```

Или так (с обещаниями):

```suggestion
            "can_description": "Настроено в /etc/network/interfaces. Доступно управление через NetworkManager - это более современный сервис настройки, поддержка которого сейчас развивается в Wiren Board. Для перехода на NetworkManager удалите и создайте соединение заново",
```

2022-11-21 06:17 UTC, KraPete commented on wb-network.schema.json
> +            "can_description": "Настроено в /etc/network/interfaces. Если необходимо настроить это соединение в NetworkManager'е, удалите и создайте новое",
Поменял

2022-11-21 06:25 UTC, webconn approved these changes

2022-11-21 06:29 UTC, merged