Connection Manager: don't change modem SIM slot if it's already set t…
wirenboard/wb-nm-helper pull request #24
Opened 2022-12-23 10:12 UTC by lostpoint-ru

…o proper value

2022-12-23 11:12 UTC, webconn approved these changes

2022-12-26 07:46 UTC, KraPete requested changes

2022-12-26 07:46 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        if sim_slot != modem_manager.get_primary_sim_slot(dev_path):
`NM_SETTINGS_GSM_SIM_SLOT_DEFAULT` - значит конкретный слот не прописан в настройках соединения, т.е. соединение должно подниматься на активном слоте. У тебя же будет переключение на слот `-1` и ошибка.

2022-12-26 07:46 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        self, con: NMConnection, dev_path, timeout: datetime.timedelta
`dev_path: str`

2022-12-26 07:55 UTC, KraPete approved these changes

2022-12-26 08:31 UTC, webconn approved these changes

2022-12-26 09:03 UTC, merged