add sticky connection feature
wirenboard/wb-nm-helper pull request #25
Opened 2022-12-27 15:45 UTC by lostpoint-ru

2022-12-28 05:11 UTC, KraPete commented
Я не совсем понял зачем это? Если у нас gsm соединение, то оно принудительно висит 15 минут до проверки доступности других соединений?
Я бы понял, если бы мы проверяли более приоритетное соединение gsm раз в 15 минут. Для этого достаточно сделать отдельный таймаут для повторной активации вместо `CONNECTION_ACTIVATION_RETRY_TIMEOUT`

2022-12-28 06:12 UTC, webconn commented
Вчитался в код и тоже подумал, что получилось не совсем то. Идея была в том, чтобы ограничить переключения симок, а переключать соединения разной природы мы можем относительно безболезненно.

Можно было бы этот `sticky_timeout` переименовать, например, в `deny_sim_switch_until` (который выставлять при успешном подъёме GSM-соединения с доступным интернетом) и в обычной `check()` запрещать переключать симку до этого момента.

2022-12-28 11:27 UTC, webconn reviewed
На вид вроде хорошо, ещё можно этот параметр сразу в схему добавить, чтобы он в web-интерфейсе в редакторе появился
https://github.com/wirenboard/wb-nm-helper/blob/main/wb-network.schema.json

2022-12-30 02:48 UTC, webconn commented
После появления более подробных логов стало заметно, что есть проблемы с выставлением sticky period:

```
...
Dec 30 02:33:11 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Current connection changed to wb-gsm-sim1                                                                                                                                                                                      
Dec 30 02:33:11 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:New active connection is GSM, not changing SIM slots until 2022-12-30T02:35:11.523673                                                                                                                                          
Dec 30 02:33:36 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection Phone                                                                                                                                                                                            
Dec 30 02:34:02 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim2                                                                                                                                                                                      
Dec 30 02:34:03 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:SIM switch disabled until 2022-12-30T02:35:11.523673, not changing SIM                                                                                                                                                         
Dec 30 02:35:09 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection Phone                                                                                                                                                                                            
Dec 30 02:35:36 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim2                                                                                                                                                                                      
Dec 30 02:35:50 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Changed SIM slot                                                                                                                                                                                                               
Dec 30 02:35:50 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim1                                                                                                                                                                                      
Dec 30 02:36:01 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Changed SIM slot                                                                                                                                                                                                               
Dec 30 02:36:10 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Activated connection wb-gsm-sim1                                                                                                                                                                                               
Dec 30 02:36:38 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection Phone                                                                                                                                                                                            
Dec 30 02:37:05 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim2                                                                                                                                                                                      
Dec 30 02:37:15 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Changed SIM slot                                                                                                                                                                                                               
Dec 30 02:37:16 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim1
Dec 30 02:37:26 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Changed SIM slot
Dec 30 02:37:35 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Activated connection wb-gsm-sim1
Dec 30 02:38:08 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection Phone
Dec 30 02:38:34 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim2
Dec 30 02:38:46 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Changed SIM slot
Dec 30 02:38:46 wirenboard-ATHFDT4L wb-connection-manager[32006]: INFO:root:Trying to activate connection wb-gsm-sim1
...
```

Приоритеты настроил как `[Phone, wb-gsm-sim2, wb-gsm-sim1]`, SIM в первом слоте (чтобы периодически проверялся второй слот). Sticky период 2 минуты.

По логам видно, что выставление sticky периода сделалось только один раз в начале, после чего симки переключаются чаще, чем раз в две минуты и это не сопровождается записями про `SIM switch disabled until`

2022-12-30 05:27 UTC, KraPete requested changes
1. Меня смущает число сообщений в логе, стоит оценить нужны ли они и как выводить их только в моменты ключевых событий
2. Было бы классно сделать тест на переключение. Сформировать последовательность состояний соединений и проверить, что всё переключается верно. Тем более Николай нашёл как dbus замокать. Правда это потребует переработки кода, чтоб время вынести во вне

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                        logging.info('Changed SIM slot')
Может, в `debug`, а то оно будет сыпать раз в 15 минут в лог? И номер слота тогда ещё выводить.

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        logging.info("Timeout reached while trying to change SIM slot")
Тут тоже сомнительно. Надо ли это в `info`? Не будет ли слишком много сообщений?

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                logging.info('SIM switch disabled until {}, not changing SIM'.format(self.deny_sim_switch_until.isoformat()))
Тоже стоит в `debug`

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        logging.info('Trying to activate connection {}'.format(cn_id))
Тоже в `debug`

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +            logging.warning('"%s" is not found', cn_id)
Я пропишу левое соединение в настройках и это сообщение мне будет кучу раз валиться. Тут либо вернуть в `debug`, либо фильтр настраивать, чтоб оно один раз выпало в лог

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +            logging.warning('Device for connection "%s" is not found', cn_id)
Тут тоже спамить будет

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                logging.info('Activated connection {}'.format(cn_id))
Стоит оценить насколько часто оно будет выдаваться в лог

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +        logging.debug('check()')
Везде были человекочитаемые сообщения, а тут что-то странное

2022-12-30 05:27 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                        active_connections.get(cn_id).get_property("State") == NM_ACTIVE_CONNECTION_STATE_ACTIVATED:
Если соединение в списке, но не в состоянии `NM_ACTIVE_CONNECTION_STATE_ACTIVATED`, мы попытаемся его активировать повторно. Так и задумано? Не получим ли мы ошибку от NM?

2022-12-30 07:11 UTC, webconn commented
> 1. Меня смущает число сообщений в логе, стоит оценить, нужны ли они, и как выводить их только в моменты ключевых событий

Это я пожаловался, что в логах без дебага было недостаточно сообщений, чтобы разобраться с переключением SIM. Сейчас стало излишне много на мой вкус, правда.

2023-01-10 14:33 UTC, webconn requested changes
Плюс комментарии Петра

2023-01-10 14:33 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +                logging.info('SIM switch disabled until {}, not changing SIM'.format(
```suggestion
                logging.debug('SIM switch disabled until {}, not changing SIM'.format(
```

Кажется, будет наваливать в логи иначе

2023-01-10 14:33 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +                logging.info('SIM switch disabled until {}, not changing SIM'.format(
```suggestion
                logging.debug('SIM switch disabled until {}, not changing SIM'.format(
```

2023-01-10 14:33 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +            logging.warning('"%s" is not found', cn_id)
Вот тут не совсем согласен, левое соединение в настройках - это повод почитать варнинги. Можно было бы сделать ratelimit в этом месте, но питон так не умеет из коробки

2023-01-10 14:33 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +                logging.info('Activated connection {}'.format(cn_id))
Кажется, в  этом же файле в строке 339 уже есть запись, которая будет выводиться при переключении соединений, тоже можно в дебаг превратить

2023-01-10 15:54 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +                        logging.info('Changed SIM slot')
Номер слота добавлен в недавних правках, а вывод в INFO согласован с Никитой

2023-01-10 15:56 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +            logging.warning('"%s" is not found', cn_id)
Я считаю что если юзер прописал руками левое соединение в конфиг -- то ССЗБ и ругань в логах более чем заслужил.

2023-01-10 15:58 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +        logging.debug('check()')
Это чисто технический дебаг изначально. Сделаю более человекопонятным, да.

2023-01-10 15:58 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +                        active_connections.get(cn_id).get_property("State") == NM_ACTIVE_CONNECTION_STATE_ACTIVATED:
Так задумано, да, я обращался к Никите ровно с этим же вопросом.

2023-01-10 16:27 UTC, webconn approved these changes
Получай лайк от Петра и вливай

2023-01-11 07:08 UTC, KraPete requested changes

2023-01-11 07:08 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    def hit_connection_retry_timeout(self, cn_id):
Type hints бы добавить

2023-01-11 07:08 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +                        if self.current_connection != cn_id:
Может эту проверку положить в `current_connection_changed`?

2023-01-11 07:08 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    def current_connection_changed(self, active_cn, cn_id):
Type hints бы добавить

2023-01-11 11:36 UTC, KraPete approved these changes
Только убрать странный редактор и ок

2023-01-11 11:36 UTC, KraPete commented on wb-network.schema.json
> +                            "_format": "edWb",
Зачем тут такой редактор, я б убрал?

2023-01-11 12:35 UTC, merged