Various fixes
wirenboard/wb-nm-helper pull request #3
Opened 2022-11-08 12:09 UTC by KraPete

* Hide old web-configurator for /etc/network/interfaces
  * Fix displaying of Wi-Fi ans CAN connections defined in /etc/network/interfaces
  * Fix parsing of /etc/network/interfaces with only comments
  * Disable hostapd and dnsmasq when creating Wi-Fi AP managed by NetworkManager
  * Add Readme.md

2022-11-08 12:22 UTC, webconn requested changes

2022-11-08 12:22 UTC, webconn commented on wb-network.schema.json
>                              "type": "string",
А в NM-типах специально нет `title`?

2022-11-08 12:22 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> +        os.system("systemctl disable dnsmasq")
Меня всё ещё смущает это место. `systemctl disable` не имеет особого смысла, потому что при обновлении фитом всё взорвётся. Лучше для этих сервисов `ExecCondition` добавить со скриптом. Более того, для `hostapd` @ekateluv  уже такой скрипт делала, и вроде как он покрывает случай, описанный тут. Можно его же просто для `dnsmasq` прописать заодно.

2022-11-08 12:40 UTC, ekateluv commented on wb/nm_helper/network_manager_adapter.py
> +        os.system("systemctl disable dnsmasq")
https://github.com/wirenboard/wb-configs/blob/master/configs/etc/systemd/system/hostapd.service.d/override.conf

2022-11-08 12:53 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +        os.system("systemctl disable dnsmasq")
Была точка доступа, описанная в /etc/network/interfaces, dnsmasq и hostapd запущены. Мы удалили через web-интерфейс это описание и сделали всё через NM. В результате NM и dnsmasq подерутся, точка не поднимется.
`ExecCondition` я могу добавить для перезагрузки контроллера и убрать `disable`, но в момент переконфигурирования всё равно надо останавливать сервисы.

2022-11-08 12:56 UTC, KraPete commented on wb-network.schema.json
>                              "type": "string",
Да, там нет кнопочки "Свойства", где выводится это название. Вообще это баг json-editor'а. Параметр отмечен как скрытый, поэтому следов его в web-интерфейсе быть не должно. Но он зачем то отображается, причём он не интерактивный.
![изображение](https://user-images.githubusercontent.com/86825564/200570427-52b8af96-4a20-46d0-8f3a-2d95a78676d7.png)

2022-11-08 13:22 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> +        os.system("systemctl disable dnsmasq")
Останавливать сервисы - ок, я про disable в первую очередь

2022-11-09 10:44 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +        os.system("systemctl disable dnsmasq")
Сделал

2022-11-09 10:55 UTC, webconn approved these changes

2022-11-09 11:09 UTC, merged