Add 'DNS servers'/'DNS search domains' options
wirenboard/wb-nm-helper pull request #31
Opened 2023-01-12 06:53 UTC by sikmir

2023-01-12 07:05 UTC, KraPete requested changes

2023-01-12 07:05 UTC, KraPete commented on wb-network.schema.json
> +                    "type": "string",
Возможно, тут надо какую-то валидацию. Пользователь может ввести что угодно, и у нас вывалится исключение внутри wb-nm-helper. В результате пользователь не будет знать, что что-то пошло не так.

2023-01-12 17:58 UTC, sikmir commented on wb-network.schema.json
> +                "dns": {
Добавил:
<img width="395" alt="Screen Shot 2023-01-12 at 20 57 06" src="https://user-images.githubusercontent.com/688044/212143153-da725701-71f1-42ea-8434-a63db9ec4f4e.png">

2023-01-12 18:00 UTC, sikmir commented on wb-network.schema.json
> +                "dns-search": {
добавил

2023-01-12 18:17 UTC, sikmir commented on wb-network.schema.json
> +                    "type": "string",
Если проверять регэксом, то будет как-то совсем уж громоздко, и при этом все равно не даст гарантии валидности. Правильно бы было валидировать на бэкенде и сообщать в UI об ошибках, но такого у нас пока нет.

2023-01-13 03:24 UTC, sikmir commented on wb-network.schema.json
> +                    "type": "string",
Даже если туда ввели какой-тот мусор, просто вылетит ошибка и ничего не сохранится в конфиг.

2023-01-13 06:00 UTC, KraPete approved these changes

2023-01-13 06:53 UTC, merged