Feature/57358 cm connectivity config
wirenboard/wb-nm-helper pull request #37
Opened 2023-01-17 09:43 UTC by lostpoint-ru

2023-01-17 09:51 UTC, webconn requested changes

2023-01-17 09:51 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +            raise ValueError("Bad connectivity URL %s" % self.connectivity_check_url)
Я так понимаю, ты тут и ниже хотел использовать `ImpoperlyConfigured`, а то у тебя исключение определено, но нигде не бросается

2023-01-17 09:51 UTC, webconn commented on wb-network.schema.json
> +                            "title": "Connectivity Check Payload",
Я бы тут дописал в description, что мы проверяем не строгое равенство, а вхождение этой строки в ответ, потоу что вообще неочевидно

2023-01-17 09:51 UTC, webconn commented on wb-network.schema.json
> +                            "title": "Connectivity Check URL",
Надо указать, что там должно быть `http` (не `https`), или это не ограничение?
Ну и дописать, что все эти URL нужны, чтобы проверять соединение минуя captive portals

2023-01-17 09:52 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +            raise ValueError("Bad connectivity URL %s" % self.connectivity_check_url)
Тьфу, точно.

2023-01-17 10:21 UTC, lostpoint-ru commented on wb-network.schema.json
> +                            "title": "Connectivity Check URL",
в принципе, протокол тут не важен, если https -- то просто там должен быть валидный для контроллера сертификат (не самоподписный). и то, теоретически, можно на нашей стороне при проверке выставить флаг игнорирования ошибок ssl.

2023-01-17 11:38 UTC, webconn approved these changes

2023-01-18 12:08 UTC, sikmir commented on wb-network.schema.json
> +                            "title": "Connectivity Check URL",
Перевода на русский не хватает

2023-01-30 08:05 UTC, lostpoint-ru commented
Учтено в рефакторинге

2023-01-30 08:05 UTC, closed without merging