Feature/57524 tiers refactor
wirenboard/wb-nm-helper pull request #39
Opened 2023-01-23 17:34 UTC by lostpoint-ru

2023-01-24 06:58 UTC, webconn requested changes
Питоновые проверки ещё не прошли, метсами форматирование сбилось как минимум

2023-01-24 06:58 UTC, webconn commented on tests/mm_mock.py
> +class AbsFakeNMConnection(abc.ABC):
А для чего тут `ABC`?

2023-01-24 06:58 UTC, webconn commented on tests/mm_mock.py
> +            return [self.name]  # FIXME: make more accurate
Надо ещё название интерфейса отдельным сделать?

2023-01-24 06:58 UTC, webconn commented on tests/test_connection_manager.py
> +class ConnectionManagerCheckTests(unittest.TestCase):
Если тестим через pytest, можно не делать эти классы (тем более, что setup/teardown не делаешь). В следующем файле ведь нету уже

2023-01-24 06:58 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    def get_tiers(cfg: Dict) -> List[ConnectionTier]:
Возвращаемый тип тут не `List`, тут будет `Iterator`
https://stackoverflow.com/questions/50154754/confusion-of-annotating-generator-function-as-iterator

2023-01-24 06:58 UTC, webconn commented on wb-network.schema.json
> +                                    "type": "array",
По-моему определение параметров можно было в `definitions` перетащить, чтобы три раза не копипастить

2023-01-24 06:58 UTC, webconn commented on tests/test_connection_manager_timeouts.py
> +        assert timeout >= delta.total_seconds() >= (timeout - 5)
Не очень хороший тест. Если внутри твоего кода вызывается `datetime.now()`, лучше его замокать и тут сравнивать уже известные заранее значения. Остальных тестов это тоже касается

2023-01-25 07:48 UTC, lostpoint-ru commented on tests/mm_mock.py
> +class AbsFakeNMConnection(abc.ABC):
убрал

2023-01-25 12:08 UTC, lostpoint-ru commented on tests/mm_mock.py
> +            return [self.name]  # FIXME: make more accurate
Тут я сам не определился. 

С одной стороны -- с точки зрения перфекционизма, внутри FakeNetworkManager можно реализовать полностью всю инфраструктуру не только соединений, но и ассоциированных с ними интерфейсов. 

С другой -- переключалка сама абсолютно по минимуму вникает в тему интерфейсов и чаще всего получает их из NM, проверяет их на то что они не пустое значение, после чего передают их еще куда-то в NM и после этого забывают про них. 

Поэтому пока считерил и реализовал тему интерфейсов малой кровью, без полноценного менеджмента. Для тестирования переключалки этого достаточно, нужно ли тут подходить с фанатизмом -- можно обсудить)

2023-01-25 12:09 UTC, lostpoint-ru commented on tests/test_connection_manager.py
> +class ConnectionManagerCheckTests(unittest.TestCase):
Обновил тесты, теперь замечание неактуально, наверное.

2023-01-25 12:09 UTC, lostpoint-ru commented on tests/test_connection_manager_timeouts.py
> +        assert timeout >= delta.total_seconds() >= (timeout - 5)
Переделал, вынес now() в метод TimeoutManager.now() и замокал в тестах, спасибо)

2023-01-26 10:20 UTC, webconn requested changes

2023-01-26 10:22 UTC, webconn commented
Думаю, надо выводить это из драфта, привести в порядок форматирование и жалобы линтера, и ревьювить уже всем вместе

2023-02-09 07:51 UTC, webconn requested changes

2023-02-09 15:04 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +        self.modem_manager = modem_manager or ModemManager()
Раньше он был захардкоженным, ради тестов сделал возможность его опционального оверрайда чем-то выданным снаружи.

Можно убрать дефолтовое значение и в явном виде требовать его подачи.

2023-02-09 15:06 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +        return count
сделаю, угу

2023-02-09 15:13 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +            yield ConnectionTier(name, level, cfg.get("tiers", {}).get(name, []))
причешу

2023-02-21 13:47 UTC, lostpoint-ru commented on tests/test_connection_manager.py
> +            self.con_man.timeouts.deny_sim_switch_until = None
Так, я посмотрел внимательнее и на самом деле это совсем не cleanup, это моделирование состояния различных таймаутов для проверки того, насколько корректно отрабатывает метод ok_to_activate(), учитывающий состояния различных таймаутов.

Не очень соображу сходу, как тут сделать неинвазивно, тем более что вторгаемся мы не в тот объект, который тестируем, а в таймаут-менеджер.

2023-02-21 13:50 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +        # no working connections found at all
Почему единожды? Мне кажется, его надо выводить в дебаг, но всякий раз, когда ситуация наблюдается -- оно как раз описывает текущую обстановку и помогает понять, что происходит унутре менеджера.

2023-02-21 14:13 UTC, lostpoint-ru commented on tests/test_connection_manager.py
> +            self.con_man.timeouts.deny_sim_switch_until = None
Хотя вру, там частично есть api для неинвазивной манипуляции состояниями таймаутов (для соединений да, для стики-сим -- нет)

2023-02-27 16:09 UTC, webconn commented
rebased in #48

2023-02-27 16:09 UTC, closed without merging