Feature/59004 wifi sticky
wirenboard/wb-nm-helper pull request #52
Opened 2023-03-09 07:12 UTC by lostpoint-ru

2023-03-10 06:33 UTC, KraPete requested changes

2023-03-10 06:33 UTC, KraPete commented on tests/test_connection_manager.py
> +# class GetSimSlotsTests(AbsConManTests):
Почему закоментировано?

2023-03-10 06:36 UTC, lostpoint-ru commented on tests/test_connection_manager.py
> +# class GetSimSlotsTests(AbsConManTests):
Тест стал неактуальным, т.к. метод уехал из ConnectionManager в NMConnection, а его мы вообще подменяем в рамках системы тестов и протестировать именно продуктовый NMConnection.get_sim_slot() сейчас возможности нет.

2023-03-10 06:42 UTC, KraPete commented on tests/test_connection_manager.py
> +# class GetSimSlotsTests(AbsConManTests):
Тогда удаляй

2023-03-10 09:02 UTC, lostpoint-ru commented on debian/changelog
> +wb-nm-helper (1.20.1) stable; urgency=medium
увеличил minor

2023-03-10 09:03 UTC, lostpoint-ru commented on tests/test_connection_manager.py
> +# class GetSimSlotsTests(AbsConManTests):
Выпилил )

2023-03-13 10:10 UTC, KraPete approved these changes

2023-03-13 16:19 UTC, webconn approved these changes

2023-03-14 06:40 UTC, merged