Feature/59434 bugfixes
wirenboard/wb-nm-helper pull request #53
Opened 2023-03-23 14:04 UTC by lostpoint-ru

- ConnectionManagerConfigFile теперь валидирует соединения (и взятые из конфига, и полученные автоконфигуратором) на предмет managed=True
- ConnectionManager.check_connectivity() теперь статический метод (по просьбе ekateluv)
- Ошибка инициализации ModemManager теперь обратабывается и не приводит к безвременной кончине сервиса

2023-03-24 08:54 UTC, webconn requested changes

2023-03-24 08:54 UTC, webconn commented on tests/mm_mock.py
> +            if kwarg in ("managed",):
```suggestion
            if kwarg == "managed":
```

2023-03-24 08:54 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    def check_connectivity(active_cn: NMActiveConnection, config: ConnectionManagerConfigFile) -> bool:
Я думаю, что эту функцию и `curl_get` надо выносить из класса. Они ничего особо общего с ним теперь не имеют, пользуются только друг другом. Тем более если это теперь часть API (переиспользуется в другом месте)

2023-03-24 08:54 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    def __init__(self, network_manager: INetworkManager) -> None:
Не знаю, делать ли сейчас что-то с этим или нет, но этот класс стал делать слишком много вещей одновременно. Насколько я понимаю, когда он переиспользуется в коде сервиса, публикующего статусы соединений (у Кати), там не нужна проверка на `managed`, только настройки `connectivity_check_*`.

Решений я тут вижу несколько: либо делать для этого класса обёртку с проверкой managed-флагов, либо переносить проверку managed-флагов в код выше по стеку ещё как-то, либо завозить `network_manager` как аргумент только в те методы, где он непосредственно используется.

Вообще тут две разные логические сущности получаются, файл конфига и его дополненная автогенерированная версия с поправкой на managed, так что два разных вложенных класса тут вроде лучше подходят.

2023-03-28 14:18 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +    def __init__(self, network_manager: INetworkManager) -> None:
Запилил изменения по этим обсуждениям.

2023-03-28 14:18 UTC, lostpoint-ru commented on wb/nm_helper/connection_manager.py
> +    def check_connectivity(active_cn: NMActiveConnection, config: ConnectionManagerConfigFile) -> bool:
Вынес, сделал максимально портативными.

2023-03-28 14:42 UTC, webconn reviewed
По коду вроде ок, пойду на контроллере проверю

2023-03-28 14:42 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    init_logging(cfg_json.get("debug", False))  # must be initialized before ConnectionManagerConfigFile
```suggestion
    init_logging(cfg_json.get("debug", False))  # must be initialized before NetworkAwareConfigFile
```

2023-03-28 14:42 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    active_cn: NMActiveConnection, config: ConfigFile or NetworkAwareConfigFile = None
Тут и в остальных местах этот `or NetworkAwareConfigFile` не нужен, он ведь наследуется от `ConfigFile`

2023-03-28 15:19 UTC, webconn approved these changes

2023-03-30 07:16 UTC, merged