Add support for multiple iface options
wirenboard/wb-nm-helper pull request #55
Opened 2023-03-27 23:06 UTC by sikmir

1. https://manpages.debian.org/bullseye/ifupdown/interfaces.5.en.html#FILE_FORMAT:

> Lines starting with # are ignored. Note that end-of-line comments are NOT supported, comments must be on a line of their own.

То есть в `pre-up wb-set-mac # comment1` согласно формату нет комментария и поэтому парсится как часть команды `wb-set-mac # comment1`.

2. https://manpages.debian.org/bullseye/ifupdown/interfaces.5.en.html#IFACE_OPTIONS:

> The following "command" options are available for every family and method. Each of these options can be given multiple times in a single stanza, in which case the commands are executed in the order in which they appear in the stanza.

Чинит проблему, что если вручную сконфигурить несколько например `pre-up` комманд, то при сохранении конфига из UI запишется только одна из них.

3. Добавлен хидер `# This file is automatically generated by wb-nm-helper.` в `/etc/network/interfaces`

2023-03-28 05:35 UTC, KraPete requested changes
1. Если в значении параметра в начале стоит `#`, этот параметр не попадает в homeui.
`hostname #WirenBoard`
2. Выглядит убого
![image](https://user-images.githubusercontent.com/86825564/228137858-92b1d359-28f4-4b89-a584-f456b9352c87.png)
3. Если есть только один параметр, никак не добавить второй такой же. Только редактировать json

Предлагаю все известные параметры отображать как сейчас, а остальные в отдельном массиве `название - значение`, так будет аккуратнее.

2023-03-28 05:35 UTC, KraPete commented on tests/test_network_interfaces_adapter.py
> +    assert adapter.format().replace("\n", "") == generated.replace("\n", "")
Зачем так?

2023-03-28 05:35 UTC, KraPete commented on wb-network.schema.json
> +                    "type": ["array", "string"],
Это вообще не используется, весь `_properties_that_are_not_used_for_now` можно выкинуть

2023-03-28 07:11 UTC, sikmir commented
> 1. Если в значении параметра в начале стоит `#`, этот параметр не попадает в homeui.
>        `hostname #WirenBoard`

поправил

2023-03-28 07:32 UTC, sikmir commented on tests/test_network_interfaces_adapter.py
> +    assert adapter.format().replace("\n", "") == generated.replace("\n", "")
убрал replace

2023-03-28 07:33 UTC, webconn commented
> 1. Если в значении параметра в начале стоит `#`, этот параметр не попадает в homeui.
>        `hostname #WirenBoard`

А так вообще можно? @KraPete

2023-03-28 07:38 UTC, sikmir commented
> > 1. Если в значении параметра в начале стоит `#`, этот параметр не попадает в homeui.
> >    `hostname #WirenBoard`
> 
> А так вообще можно? @KraPete

Например случай `pre-up #foo` вполне валидный, в результате должна выполниться комманда `#foo` (то есть ничего). Если же как сейчас распарсит как комментарий (а это не комментарий с тз формата interfaces), то сломается осттальной парсинг.

2023-03-28 08:01 UTC, KraPete commented
> > 1. Если в значении параметра в начале стоит `#`, этот параметр не попадает в homeui.
> >    `hostname #WirenBoard`
> 
> А так вообще можно? @KraPete

У меня в пароле к точке доступа есть `#` в начале

2023-03-28 13:58 UTC, sikmir commented on wb-network.schema.json
> +                    "type": ["array", "string"],
убрал

2023-03-28 22:02 UTC, sikmir commented
> Предлагаю все известные параметры отображать как сейчас, а остальные в отдельном массиве название - значение, так будет аккуратнее.

<img width="596" alt="Näyttökuva 2023-3-29 kello 1 48 18" src="https://user-images.githubusercontent.com/688044/228374684-9180ca2e-b7a4-4d78-9cf1-2a35090dedfc.png">

Вот так выглядит уже лучше, отображать табличкой только `pre-*` и `post-*` опции, так как только они могут встречаться >1 раза.

2023-03-29 05:02 UTC, KraPete requested changes
Давай, уберём:
1. Кнопочку сворачивания рядом с Pre-up commands
2. Кнопки удаления последней строки и всех строк
3. `Same as up commands`

Надо сделать название для элементов массива, чтоб там не `row` писалось

Надо перевод для pre-up  и т.п.

2023-03-29 05:18 UTC, sikmir commented
> Давай, уберём:
> 
>     1. Кнопочку сворачивания рядом с Pre-up commands
> 
>     2. Кнопки удаления последней строки и всех строк
> 
>     3. `Same as up commands`
> 
> 
> Надо сделать название для элементов массива, чтоб там не `row` писалось
> 
> Надо перевод для pre-up и т.п.

<img width="520" alt="Näyttökuva 2023-3-29 kello 9 16 30" src="https://user-images.githubusercontent.com/688044/228433741-ac9da675-3109-4ab4-8b6c-ed8ba5481782.png">

2023-03-29 06:15 UTC, KraPete approved these changes

2023-03-29 06:51 UTC, merged