Add ReloadPropagatedFrom to wb-mqtt-nm-helper
wirenboard/wb-nm-helper pull request #62
Opened 2023-04-19 13:09 UTC by ekateluv

Добавлена зависимость публикатора по сигналу перезагрузки от сервиса wb-connection-manager. При смене URL для проверки соединения получается так, что скрипт nm_helper.py дергает network manager и тот обновляет соединения быстрее, чем confed переписывает конфиг. Вследствие этого wb-mqtt-nm-helper сервис проверяет коннективити по старым настройкам.
После обновления конфига конфед перезапускает connection manager. Поэтому, чтобы mqtt-nm-helper обновлялся с новым конфигом, решили привязать перезагрузку connection-manager`а конфедом (которая происходит после записи конфига) к перезагрузке пуликатора
______________________________________
Изменилась концепция решения. Чтобы не перезапускать публикатор всякий раз, сделали ему ручку reload. За нее должен дергать confed. Сначала переписывается конфиг, потом через 4с перезапускается connection manager, потом делается reload wb-mqtt-nm-helper, также через 4с

__________________________________
Теперь нет постоянных таймаутов. Сервис выполняет reload по завершению sync() на файле конфига после записи (на стороне confed)

2023-04-21 04:11 UTC, KraPete commented on debian/changelog
> +  * Add some exceptions handlind
```suggestion
  * Add some exceptions handling
```

2023-04-21 04:15 UTC, KraPete commented on wb/nm_helper/virtual_devices.py
> +                except dbus.exceptions.DBusException:
Что здесь может случиться?

2023-04-21 04:15 UTC, KraPete commented on wb/nm_helper/virtual_devices.py
> +                except dbus.exceptions.DBusException:
И здесь?

2023-04-21 11:25 UTC, ekateluv commented on wb/nm_helper/virtual_devices.py
> +                except dbus.exceptions.DBusException:
Иногда в логах падает это место. Особенно когда соединение деактивируется, там может прилететь событие что сменился ip4config, ты пытаешься его вычитать, а по этому пути уже ничего нет, потому что на самом деле тебе уже пришло новое событие, что ip4config стал пуст, просто ты еще старое не обработал

2023-04-21 11:27 UTC, ekateluv commented on wb/nm_helper/virtual_devices.py
> +                except dbus.exceptions.DBusException:
То же самое примерно. Так как имя девайса это не свойство дбас-объекта соединения, то там прилетает событие что новый девайс и путь к нему. Чтобы прочитать имя, тебе надо по этому пути сходить и прочитать. Поэтому при деактивации соединения приходит что сменился девайс, ты пытаешься его прочитать, а там уже на самом деле ничего нет, потому что скрипт работает медленнее чем события происходят. При деактивации соединений тут все время вылетает, если не обработать

2023-04-21 11:41 UTC, KraPete approved these changes

2023-04-25 13:16 UTC, webconn requested changes

2023-04-25 13:16 UTC, webconn commented on wb/nm_helper/virtual_devices.py
> +        signal.pidfd_send_signal(pid_fd, signal.SIGHUP)
Не очень подходящий сигнал, если честно. Почему не какой-нибудь `SIGUSR1`?

2023-04-25 13:16 UTC, webconn commented on wb/nm_helper/virtual_devices.py
> +            self._connectivity_updater.update(active_connection)
Тут может быть гонка со старыми запросами, раз мы их тут не отменяем, я бы подумал сразу в эту сторону. Простая ситуация - при старых настройках мы долго ждали соединения с проверочным сервером, потом конфиг перезагрузили, быстро проверили соединение на новых настройках, а потом старая таска не дождалась, вылетела по таймауту и сказала, что интернета нет

2023-04-25 14:49 UTC, ekateluv commented on wb/nm_helper/virtual_devices.py
> +        signal.pidfd_send_signal(pid_fd, signal.SIGHUP)
В новых версиях systemd посылается именно такой при reload. Будь у нас версия systemd свежее, я бы не руками генерировала сигнал, а SIGHUP сам бы появился

2023-04-25 14:51 UTC, ekateluv commented on wb/nm_helper/virtual_devices.py
> +            self._connectivity_updater.update(active_connection)
в классе ConnectivityUpdater есть словарь активное соединение - фьючерс запроса проверки коннективити. Как только приходит запрос на проверку сначала смотрим, есть ли фьючерс в массиве. если есть - отменяем старый, планируем новый. Эта логика уже была влита

2023-04-25 14:55 UTC, ekateluv commented on debian/changelog
> +  * Add some exceptions handlind
поправлено

2023-04-25 14:56 UTC, ekateluv commented on debian/control
> +         wb-mqtt-confed (>= 1.13.0),
поправлено

2023-04-25 15:05 UTC, webconn commented on wb/nm_helper/virtual_devices.py
> +        signal.pidfd_send_signal(pid_fd, signal.SIGHUP)
А, тогда принял. Интересный выбор

2023-04-28 10:54 UTC, merged