Scan Wi-Fi networks using iwlist
wirenboard/wb-nm-helper pull request #7
Opened 2022-11-11 09:30 UTC by KraPete

Сделал запрос доступных сетей через `iwlist`, теперь он работает, если настройки Wi-Fi сделаны в `/etc/netwrok/interfaces` и в режиме точки доступа. NM выдавал список сетей только в режиме клиента, если он сам управлял Wi-Fi.

2022-11-21 04:56 UTC, webconn requested changes

2022-11-21 04:56 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Кажется, стоит поудалять эти комментарии здесь и далее, однажды мы настроим pylint как надо

2022-11-21 04:56 UTC, webconn commented on wb/nm_helper/network_management_system.py
> -class INetworkManagementSystem:
А почему решил удалить? Можно было бы сделать его через `abc` и тогда питон ругался бы на недоопределённые методы, плюс автодополнение с аннотациями работало бы

2022-11-21 04:56 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> +        # pylint: disable=no-self-use
Это лечится с помощью `@staticmethod`

2022-11-21 04:56 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> -    def scan_if_needed(self, dev: NMWirelessDevice) -> None:
Думаешь, стоит совсем удалять? `iwlist` - это всё-таки костыль, и я бы лучше прибегал к нему только в тех ситуациях, когда мы не можем попросить список у networkmanager

2022-11-21 04:56 UTC, webconn commented on wb/nm_helper/nm_helper.py
> +    return "wlan0"
Не сошёлся тип с аннотацией

2022-11-21 06:18 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Вот настроим, удалю. Пока я руками запускаю pylint и хочу ивдеть только новые ошибки

2022-11-21 06:19 UTC, KraPete commented on wb/nm_helper/network_management_system.py
> -class INetworkManagementSystem:
Общих методов почти не осталось, и я теперь везде с конкретными классами работаю.

2022-11-21 06:22 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> -    def scan_if_needed(self, dev: NMWirelessDevice) -> None:
NM умеет сканировать сети, только, если поднят клиент или интерфейс не занят. Причём ему надо, чтобы интерфейс не упоминался в `interfaces`. `iwlist` умеет сканировать и в режиме точки доступа, ему не важно, кто управляет интерфейсом. Пока костыль - это NM.

2022-11-21 06:27 UTC, KraPete commented on wb/nm_helper/nm_helper.py
> +    return "wlan0"
Убрал, это не надо вообще

2022-11-21 06:36 UTC, KraPete commented on wb/nm_helper/network_manager_adapter.py
> +        # pylint: disable=no-self-use
Поменял

2022-11-21 06:57 UTC, webconn commented on wb/nm_helper/network_manager_adapter.py
> -    def scan_if_needed(self, dev: NMWirelessDevice) -> None:
Считай, что убедил, хотя мне это и не нравится. Тогда добавляй `wireless-tools` в зависимости пакета

2022-11-21 06:58 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Ты же это у себя проверяешь? На CI ничего не настроено

2022-11-21 07:36 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
На CI не ставятся зависимости перед проверкой, и pylint на них ругается

2022-11-21 07:38 UTC, webconn commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Да, я знаю. Ты в итоге это у себя локально проверяешь? Что-то мешает локально установить нужные пакеты?

2022-11-22 06:45 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Раз
https://stackoverflow.com/questions/28437071/pylint-1-4-reports-e1101no-member-on-all-c-extensions
А потом появляется это
```
wb/nm_helper/connection_manager.py:100:16: E1101: Instance of 'Curl' has no 'URL' member (no-member)
wb/nm_helper/connection_manager.py:101:16: E1101: Instance of 'Curl' has no 'WRITEDATA' member (no-member)
wb/nm_helper/connection_manager.py:102:16: E1101: Instance of 'Curl' has no 'INTERFACE' member (no-member)
```
Делаем два
https://stackoverflow.com/questions/33961756/disabling-pylint-no-member-e1101-error-for-specific-libraries

т.е. в pylintrc
```
+ extension-pkg-allow-list=pycurl
+ generated-members=pycurl.Curl.*
```

2022-11-22 06:47 UTC, KraPete commented on wb/nm_helper/connection_manager.py
> +    # pylint: disable=c-extension-no-member
Убрал хинты, чтоб уже влить

2022-11-22 07:39 UTC, webconn commented
Связанный PR: https://github.com/wirenboard/codestyle/pull/33

2022-11-22 07:40 UTC, webconn approved these changes

2022-11-22 09:44 UTC, merged

2022-11-22 18:54 UTC, sikmir commented on debian/changelog
> +wb-nm-helper (1.10.0) stable; urgency=medium
Почему сразу 1.10.0?

2022-11-23 04:31 UTC, KraPete commented on debian/changelog
> +wb-nm-helper (1.10.0) stable; urgency=medium
Точно. Промазал с версией :( @webconn Заменим?